spring:
  profiles:
    include: secure
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    port: 6379
    host: localhost
logging:
  level:
    com.mmt: DEBUG