spring:
  profiles:
    include: secure
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    com.mmt: DEBUG
    org:
      springframework:
        data:
          neo4j: DEBUG
