spring:
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: "jdbc:mysql://${RDB_URL:localhost}:${RDB_PORT}/${RDB_NAME}"
  #   username: ${RDB_USERNAME}
  #   password: ${RDB_PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  neo4j:
    uri: bolt://${GDB_URL:localhost}:${GDB_PORT}
    authentication:
      username: ${GDB_USERNAME}
      password:  ${GDB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: https://www.my-math-teacher.com/login/oauth2/code/google
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: e${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              # - mobile
            redirect-uri: https://www.my-math-teacher.com/login/oauth2/code/code/naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            redirect-uri: https://www.my-math-teacher.com/login/oauth2/code/kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  # 1시간 / 2시간
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 7200
allowed:
  # origins: http://${EC2_IP}
  origins1: https://${EC2_DOMAIN_NAME1}
  origins2: https://${EC2_DOMAIN_NAME2}