INSERT INTO chapters VALUES (1, '몇일까요 (1)', '초등', '초1', '1학기', '', '9까지의 수');
INSERT INTO chapters VALUES (3, '몇일까요 (2)', '초등', '초1', '1학기', '', '9까지의 수');
INSERT INTO chapters VALUES (5, '몇째일까요', '초등', '초1', '1학기', '', '9까지의 수');
INSERT INTO chapters VALUES (6, '수의 순서를 알아볼까요', '초등', '초1', '1학기', '', '9까지의 수');
INSERT INTO chapters VALUES (7, '1만큼 더 큰 수와 1만큼 더 작은 수는 무엇일까요', '초등', '초1', '1학기', '', '9까지의 수');
INSERT INTO chapters VALUES (8, '어느 수가 더 클까요', '초등', '초1', '1학기', '', '9까지의 수');
INSERT INTO chapters VALUES (9, '여러 가지 모양을 찾아볼까요', '초등', '초1', '1학기', '', '여러 가지 모양');
INSERT INTO chapters VALUES (10, '여러 가지 모양을 알아볼까요', '초등', '초1', '1학기', '', '여러 가지 모양');
INSERT INTO chapters VALUES (11, '모으기와 가르기를 해 볼까요 (1)', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (14, '더하기는 어떻게 나타낼까요', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (15, '덧셈을 해 볼까요 (1)', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (16, '덧셈을 해 볼까요 (2)', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (17, '빼기는 어떻게 나타낼까요', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (18, '뺄셈을 해 볼까요 (1)', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (19, '뺄셈을 해 볼까요 (2)', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (20, '0을 더하거나 빼면 어떻게 될까요', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (21, '덧셈과 뺄셈을 해 볼까요', '초등', '초1', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (22, '어느 것이 더 길까요', '초등', '초1', '1학기', '', '비교하기');
INSERT INTO chapters VALUES (25, '어느 것에 더 많이 담을 수 있을까요', '초등', '초1', '1학기', '', '비교하기');
INSERT INTO chapters VALUES (26, '9다음 수는 무엇일까요', '초등', '초1', '1학기', '', '50까지의 수');
INSERT INTO chapters VALUES (27, '십몇을 알아볼까요', '초등', '초1', '1학기', '', '50까지의 수');
INSERT INTO chapters VALUES (29, '10개씩 묶어 세어 볼까요', '초등', '초1', '1학기', '', '50까지의 수');
INSERT INTO chapters VALUES (30, '50까지의 수를 세어 볼까요', '초등', '초1', '1학기', '', '50까지의 수');
INSERT INTO chapters VALUES (31, '수의 순서를 알아볼까요', '초등', '초1', '1학기', '', '50까지의 수');
INSERT INTO chapters VALUES (32, '어느 수가 더 클까요', '초등', '초1', '1학기', '', '50까지의 수');
INSERT INTO chapters VALUES (33, '60, 70, 80, 90을 알아볼까요', '초등', '초1', '2학기', '', '100까지의 수');
INSERT INTO chapters VALUES (34, '99까지의 수를 알아볼까요', '초등', '초1', '2학기', '', '100까지의 수');
INSERT INTO chapters VALUES (35, '수의 순서를 알아볼까요', '초등', '초1', '2학기', '', '100까지의 수');
INSERT INTO chapters VALUES (36, '어느 수가 더 클까요', '초등', '초1', '2학기', '', '100까지의 수');
INSERT INTO chapters VALUES (38, '덧셈을 해 볼까요 (1)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (39, '덧셈을 해 볼까요 (2)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (40, '덧셈을 해 볼까요 (3)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (41, '그림을 보고 덧셈을 해 볼까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (42, '뺄셈을 해 볼까요 (1)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (43, '뺄셈을 해 볼까요 (2)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (44, '뺄셈을 해 볼까요 (3)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (45, '그림을 보고 뺄셈을 해 볼까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(1)');
INSERT INTO chapters VALUES (46, '여러 가지 모양을 찾아볼까요', '초등', '초1', '2학기', '', '여러 가지 모양');
INSERT INTO chapters VALUES (47, '여러 가지 모양을 알아볼까요', '초등', '초1', '2학기', '', '여러 가지 모양');
INSERT INTO chapters VALUES (48, '여러 가지 모양을 꾸며 볼까요', '초등', '초1', '2학기', '', '여러 가지 모양');
INSERT INTO chapters VALUES (49, '세 수의 덧셈을 어떻게 할까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(2)');
INSERT INTO chapters VALUES (50, '세 수의 뺄셈을 어떻게 할까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(2)');
INSERT INTO chapters VALUES (51, '두 수를 더해 볼까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(2)');
INSERT INTO chapters VALUES (52, '10이 되는 더하기를 해 볼까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(2)');
INSERT INTO chapters VALUES (53, '10에서 빼 볼까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(2)');
INSERT INTO chapters VALUES (54, '10을 만들어 더해 볼까요 (1)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(2)');
INSERT INTO chapters VALUES (55, '10을 만들어 더해 볼까요 (2)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(2)');
INSERT INTO chapters VALUES (56, '몇 시일까요 (1)', '초등', '초1', '2학기', '', '시계 보기와 규칙 찾기');
INSERT INTO chapters VALUES (57, '몇 시일까요 (2)', '초등', '초1', '2학기', '', '시계 보기와 규칙 찾기');
INSERT INTO chapters VALUES (58, '규칙을 찾아 말해 볼까요', '초등', '초1', '2학기', '', '시계 보기와 규칙 찾기');
INSERT INTO chapters VALUES (59, '규칙을 찾아 여러 가지 방법으로 나타내어 볼까요', '초등', '초1', '2학기', '', '시계 보기와 규칙 찾기');
INSERT INTO chapters VALUES (61, '수 배열에서 규칙을 찾아볼까요', '초등', '초1', '2학기', '', '시계 보기와 규칙 찾기');
INSERT INTO chapters VALUES (63, '10을 이용하여 모으기와 가르기를 해 볼까요', '초등', '초1', '2학기', '', '덧셈과 뺄셈(3)');
INSERT INTO chapters VALUES (64, '덧셈을 해 볼까요 (1)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(3)');
INSERT INTO chapters VALUES (66, '덧셈을 해 볼까요 (3)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(3)');
INSERT INTO chapters VALUES (67, '뺄셈을 해 볼까요 (1)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(3)');
INSERT INTO chapters VALUES (69, '뺄셈을 해 볼까요 (3)', '초등', '초1', '2학기', '', '덧셈과 뺄셈(3)');
INSERT INTO chapters VALUES (70, '90보다 10만큼 더 큰 수를 알아볼까요', '초등', '초2', '1학기', '', '세 자릿수');
INSERT INTO chapters VALUES (71, '몇백을 알아볼까요', '초등', '초2', '1학기', '', '세 자릿수');
INSERT INTO chapters VALUES (72, '세 자릿수를 알아볼까요', '초등', '초2', '1학기', '', '세 자릿수');
INSERT INTO chapters VALUES (73, '각 자리의 숫자는 얼마를 나타낼까요', '초등', '초2', '1학기', '', '세 자릿수');
INSERT INTO chapters VALUES (74, '뛰어서 세어 볼까요', '초등', '초2', '1학기', '', '세 자릿수');
INSERT INTO chapters VALUES (75, '어느 수가 더 클까요', '초등', '초2', '1학기', '', '세 자릿수');
INSERT INTO chapters VALUES (76, '동그라미를 알아볼까요', '초등', '초2', '1학기', '', '여러 가지 도형');
INSERT INTO chapters VALUES (77, '세모를 알아볼까요', '초등', '초2', '1학기', '', '여러 가지 도형');
INSERT INTO chapters VALUES (78, '네모를 알아볼까요', '초등', '초2', '1학기', '', '여러 가지 도형');
INSERT INTO chapters VALUES (79, '칠교판으로 모양을 만들어 볼까요', '초등', '초2', '1학기', '', '여러 가지 도형');
INSERT INTO chapters VALUES (80, '오각형과 육각형을 알아볼까요', '초등', '초2', '1학기', '', '여러 가지 도형');
INSERT INTO chapters VALUES (81, '똑같은 모양으로 쌓아 볼까요', '초등', '초2', '1학기', '', '여러 가지 도형');
INSERT INTO chapters VALUES (82, '여러 가지 모양으로 쌓아 볼까요', '초등', '초2', '1학기', '', '여러 가지 도형');
INSERT INTO chapters VALUES (83, '덧셈을 해 볼까요 (1)', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (84, '덧셈을 해 볼까요 (2)', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (85, '덧셈을 해 볼까요 (3)', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (86, '여러 가지 방법으로 덧셈을 해 볼까요', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (87, '뺄셈을 해 볼까요 (1)', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (88, '뺄셈을 해 볼까요 (2)', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (89, '뺄셈을 해 볼까요 (3)', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (90, '여러 가지 방법으로 뺄셈을 해 볼까요', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (91, '덧셈과 뺄셈의 관계를 식으로 나타내어 볼까요', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (92, '네모의 값을 어떻게 구할 수 있을까요', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (93, '세 수의 계산을 해 볼까요', '초등', '초2', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (95, '1cm를 알아볼까요', '초등', '초2', '1학기', '', '길이 재기');
INSERT INTO chapters VALUES (96, '자로 길이를 재어 볼까요 (1)', '초등', '초2', '1학기', '', '길이 재기');
INSERT INTO chapters VALUES (97, '자로 길이를 재어 볼까요 (2)', '초등', '초2', '1학기', '', '길이 재기');
INSERT INTO chapters VALUES (98, '길이를 어림해 볼까요', '초등', '초2', '1학기', '', '길이 재기');
INSERT INTO chapters VALUES (99, '분류는 어떻게 할까요', '초등', '초2', '1학기', '', '분류하기');
INSERT INTO chapters VALUES (100, '기준에 따라 분류해 볼까요', '초등', '초2', '1학기', '', '분류하기');
INSERT INTO chapters VALUES (101, '분류하여 세어 볼까요', '초등', '초2', '1학기', '', '분류하기');
INSERT INTO chapters VALUES (102, '분류한 결과를 말해 볼까요', '초등', '초2', '1학기', '', '분류하기');
INSERT INTO chapters VALUES (103, '여러 가지 방법으로 세어 볼까요', '초등', '초2', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (104, '묶어 세어 볼까요', '초등', '초2', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (105, '2의 몇 배를 알아볼까요', '초등', '초2', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (106, '곱셈식을 알아볼까요', '초등', '초2', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (107, '곱셈식으로 나타내어 볼까요', '초등', '초2', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (108, '100이 10개인 수를 알아볼까요', '초등', '초2', '2학기', '', '네자릿수');
INSERT INTO chapters VALUES (109, '몇천을 알아볼까요', '초등', '초2', '2학기', '', '네자릿수');
INSERT INTO chapters VALUES (110, '네 자릿수를 알아볼까요', '초등', '초2', '2학기', '', '네자릿수');
INSERT INTO chapters VALUES (111, '각 자리의 숫자는 얼마를 나타낼까요', '초등', '초2', '2학기', '', '네자릿수');
INSERT INTO chapters VALUES (112, '뛰어 세어 볼까요', '초등', '초2', '2학기', '', '네자릿수');
INSERT INTO chapters VALUES (113, '어느 수가 더 클까요', '초등', '초2', '2학기', '', '네자릿수');
INSERT INTO chapters VALUES (114, '2단 곱셈구구를 알아볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (115, '5단 곱셈구구를 알아볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (116, '3단, 6단 곱셈구구를 알아볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (117, '4단, 8단 곱셈 구구를 알아볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (118, '7단 곱셈구구를 알아볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (119, '9단 곱셈구구를 알아볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (120, '1단 곱셈구구와 0의 곱을 알아볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (121, '곱셈표를 만들어 볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (122, '곱셈구구를 이용하여 문제를 해결해 볼까요', '초등', '초2', '2학기', '', '곱셈구구');
INSERT INTO chapters VALUES (123, 'cm보다 더 큰 단위를 알아볼까요', '초등', '초2', '2학기', '', '길이 재기');
INSERT INTO chapters VALUES (124, '자로 길이를 재어 볼까요', '초등', '초2', '2학기', '', '길이 재기');
INSERT INTO chapters VALUES (125, '길이의 합을 구해 볼까요', '초등', '초2', '2학기', '', '길이 재기');
INSERT INTO chapters VALUES (126, '길이의 차를 구해 볼까요', '초등', '초2', '2학기', '', '길이 재기');
INSERT INTO chapters VALUES (127, '길이를 어림해 볼까요 (1)', '초등', '초2', '2학기', '', '길이 재기');
INSERT INTO chapters VALUES (129, '몇 시 몇 분을 알아볼까요 (1)', '초등', '초2', '2학기', '', '시각과 시간');
INSERT INTO chapters VALUES (130, '몇 시 몇 분을 알아볼까요 (2)', '초등', '초2', '2학기', '', '시각과 시간');
INSERT INTO chapters VALUES (131, '여러 가지 방법으로 시각을 읽어 볼까요', '초등', '초2', '2학기', '', '시각과 시간');
INSERT INTO chapters VALUES (132, '1시간을 알아볼까요', '초등', '초2', '2학기', '', '시각과 시간');
INSERT INTO chapters VALUES (133, '하루의 시간을 알아볼까요', '초등', '초2', '2학기', '', '시각과 시간');
INSERT INTO chapters VALUES (134, '달력을 알아볼까요', '초등', '초2', '2학기', '', '시각과 시간');
INSERT INTO chapters VALUES (135, '자료를 보고 표로 나타내어 볼까요', '초등', '초2', '2학기', '', '표와 그래프');
INSERT INTO chapters VALUES (137, '그래프로 나타내어 볼까요', '초등', '초2', '2학기', '', '표와 그래프');
INSERT INTO chapters VALUES (138, '표와 그래프의 내용을 알아볼까요', '초등', '초2', '2학기', '', '표와 그래프');
INSERT INTO chapters VALUES (139, '표와 그래프로 나타내어 볼까요', '초등', '초2', '2학기', '', '표와 그래프');
INSERT INTO chapters VALUES (140, '덧셈표에서 규칙을 찾아볼까요', '초등', '초2', '2학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (141, '곱셈표에서 규칙을 찾아볼까요', '초등', '초2', '2학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (142, '무늬에서 규칙을 찾아볼까요 (1)', '초등', '초2', '2학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (143, '무늬에서 규칙을 찾아볼까요 (2)', '초등', '초2', '2학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (144, '쌓은 모양에서 규칙을 찾아볼까요', '초등', '초2', '2학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (145, '생활에서 규칙을 찾아볼까요', '초등', '초2', '2학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (146, '덧셈을 해 볼까요 (1)', '초등', '초3', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (147, '덧셈을 해 볼까요 (2)', '초등', '초3', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (148, '덧셈을 해 볼까요 (3)', '초등', '초3', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (149, '뺄셈을 해 볼까요 (1)', '초등', '초3', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (150, '뺄셈을 해 볼까요 (2)', '초등', '초3', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (151, '뺄셈을 해 볼까요 (3)', '초등', '초3', '1학기', '', '덧셈과 뺄셈');
INSERT INTO chapters VALUES (152, '선의 종류에는 어떤 것이 있을까요', '초등', '초3', '1학기', '', '평면도형');
INSERT INTO chapters VALUES (153, '각을 알아볼까요', '초등', '초3', '1학기', '', '평면도형');
INSERT INTO chapters VALUES (155, '직각삼각형을 알아볼까요', '초등', '초3', '1학기', '', '평면도형');
INSERT INTO chapters VALUES (156, '직사각형을 알아볼까요', '초등', '초3', '1학기', '', '평면도형');
INSERT INTO chapters VALUES (157, '정사각형을 알아볼까요', '초등', '초3', '1학기', '', '평면도형');
INSERT INTO chapters VALUES (158, '똑같이 나누어 볼까요 (1)', '초등', '초3', '1학기', '', '나눗셈');
INSERT INTO chapters VALUES (159, '똑같이 나누어 볼까요 (2)', '초등', '초3', '1학기', '', '나눗셈');
INSERT INTO chapters VALUES (160, '곱셈과 나눗셈의 관계를 알아볼까요', '초등', '초3', '1학기', '', '나눗셈');
INSERT INTO chapters VALUES (161, '나눗셈의 몫을 곱셈식으로 구해 볼까요', '초등', '초3', '1학기', '', '나눗셈');
INSERT INTO chapters VALUES (162, '나눗셈의 몫을 곱셈구구로 구해 볼까요', '초등', '초3', '1학기', '', '나눗셈');
INSERT INTO chapters VALUES (163, '(몇십)ⅹ(몇)을 구해 볼까요', '초등', '초3', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (164, '(몇십 몇)ⅹ(몇)을 구해 볼까요 (1)', '초등', '초3', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (165, '(몇십 몇)ⅹ(몇)을 구해 볼까요 (2)', '초등', '초3', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (166, '(몇십 몇)ⅹ(몇)을 구해 볼까요 (3)', '초등', '초3', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (167, '(몇십 몇)ⅹ(몇)을 구해 볼까요 (4)', '초등', '초3', '1학기', '', '곱셈');
INSERT INTO chapters VALUES (168, '1cm보다 작은 단위는 무엇일까요', '초등', '초3', '1학기', '', '길이와 시간');
INSERT INTO chapters VALUES (170, '길이와 거리를 어림하고 재어 볼까요', '초등', '초3', '1학기', '', '길이와 시간');
INSERT INTO chapters VALUES (171, '1분보다 작은 단위는 무엇일까요', '초등', '초3', '1학기', '', '길이와 시간');
INSERT INTO chapters VALUES (172, '시간은 어떻게 더하고 뺄까요 (1)', '초등', '초3', '1학기', '', '길이와 시간');
INSERT INTO chapters VALUES (173, '시간은 어떻게 더하고 뺄까요 (2)', '초등', '초3', '1학기', '', '길이와 시간');
INSERT INTO chapters VALUES (174, '똑같이 나누어 볼까요', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (175, '분수를 알아볼까요 (1)', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (176, '분수를 알아볼까요 (2)', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (177, '분모가 같은 분수의 크기를 비교해 볼까요', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (178, '단위분수의 크기를 비교해 볼까요', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (179, '소수를 알아볼까요 (1)', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (180, '소수를 알아볼까요 (2)', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (181, '소수의 크기를 비교해 볼까요', '초등', '초3', '1학기', '', '분수와 소수');
INSERT INTO chapters VALUES (182, '(세 자릿수)ⅹ(한 자릿수)를 구해 볼까요 (1)', '초등', '초3', '2학기', '', '곱셈');
INSERT INTO chapters VALUES (183, '(세 자릿수)ⅹ(한 자릿수)를 구해 볼까요 (2)', '초등', '초3', '2학기', '', '곱셈');
INSERT INTO chapters VALUES (184, '(세 자릿수)ⅹ(한 자릿수)를 구해 볼까요 (3)', '초등', '초3', '2학기', '', '곱셈');
INSERT INTO chapters VALUES (185, '(몇십)ⅹ(몇십), (몇십 몇)ⅹ(몇십)을 구해 볼까요', '초등', '초3', '2학기', '', '곱셈');
INSERT INTO chapters VALUES (187, '(몇십 몇)ⅹ(몇십 몇)을 구해 볼까요 (1)', '초등', '초3', '2학기', '', '곱셈');
INSERT INTO chapters VALUES (188, '(몇십 몇)ⅹ(몇십 몇)을 구해 볼까요 (2)', '초등', '초3', '2학기', '', '곱셈');
INSERT INTO chapters VALUES (189, '곱셈을 활용할 수 있어요', '초등', '초3', '2학기', '', '곱셈');
INSERT INTO chapters VALUES (190, '(몇십)÷(몇)을 구해 볼까요 (1)', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (191, '(몇십)÷(몇)을 구해 볼까요 (2)', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (192, '(몇십 몇)÷(몇)을 구해 볼까요 (1)', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (193, '(몇십 몇)÷(몇)을 구해 볼까요 (2)', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (194, '나머지가 있는 (몇십 몇)÷(몇)을 구해 볼까요 (1)', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (195, '나머지가 있는 (몇십 몇)÷(몇)을 구해 볼까요 (2)', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (196, '(세 자릿수)÷(한 자릿수)를 구해 볼까요', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (197, '나머지가 있는 (세 자릿수)÷(한 자릿수)를 구해 볼까요', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (198, '계산이 맞는지 확인해 볼까요', '초등', '초3', '2학기', '', '나눗셈');
INSERT INTO chapters VALUES (199, '원의 중심, 반지름, 지름을 알아볼까요', '초등', '초3', '2학기', '', '원');
INSERT INTO chapters VALUES (200, '원의 성질을 알아볼까요', '초등', '초3', '2학기', '', '원');
INSERT INTO chapters VALUES (201, '컴퍼스를 이용하여 원을 그려 볼까요', '초등', '초3', '2학기', '', '원');
INSERT INTO chapters VALUES (202, '원을 이용하여 어러 가지 모양을 그려 볼까요', '초등', '초3', '2학기', '', '원');
INSERT INTO chapters VALUES (203, '분수로 나타내어 볼까요', '초등', '초3', '2학기', '', '분수');
INSERT INTO chapters VALUES (204, '분수만큼 얼마일까요 (1)', '초등', '초3', '2학기', '', '분수');
INSERT INTO chapters VALUES (205, '분수만큼 얼마일까요 (2)', '초등', '초3', '2학기', '', '분수');
INSERT INTO chapters VALUES (206, '여러 가지 분수를 알아볼까요 (1)', '초등', '초3', '2학기', '', '분수');
INSERT INTO chapters VALUES (207, '여러 가지 분수를 알아볼까요 (2)', '초등', '초3', '2학기', '', '분수');
INSERT INTO chapters VALUES (208, '분모가 같은 분수의 크기를 비교해 볼까요', '초등', '초3', '2학기', '', '분수');
INSERT INTO chapters VALUES (210, '들이의 단위는 무엇일까요', '초등', '초3', '2학기', '', '들이와 무게');
INSERT INTO chapters VALUES (211, '들이를 어림하고 재어 볼까요', '초등', '초3', '2학기', '', '들이와 무게');
INSERT INTO chapters VALUES (212, '들이의 덧셈과 뺄셈을 해 볼까요', '초등', '초3', '2학기', '', '들이와 무게');
INSERT INTO chapters VALUES (214, '무게의 단위는 무엇일까요', '초등', '초3', '2학기', '', '들이와 무게');
INSERT INTO chapters VALUES (215, '무게를 어림하고 재어 볼까요', '초등', '초3', '2학기', '', '들이와 무게');
INSERT INTO chapters VALUES (216, '무게의 덧셈과 뺄셈을 해 볼까요', '초등', '초3', '2학기', '', '들이와 무게');
INSERT INTO chapters VALUES (217, '표에서 무엇을 알 수 있을까요', '초등', '초3', '2학기', '', '자료의 정리');
INSERT INTO chapters VALUES (218, '자료를 수집하여 표로 나타내어 볼까요', '초등', '초3', '2학기', '', '자료의 정리');
INSERT INTO chapters VALUES (219, '그림그래프를 알아볼까요', '초등', '초3', '2학기', '', '자료의 정리');
INSERT INTO chapters VALUES (220, '그림그래프로 나타내어 볼까요', '초등', '초3', '2학기', '', '자료의 정리');
INSERT INTO chapters VALUES (221, '1000이 10개인 수를 알아볼까요', '초등', '초4', '1학기', '', '큰 수');
INSERT INTO chapters VALUES (222, '다섯 자릿수를 알아볼까요', '초등', '초4', '1학기', '', '큰 수');
INSERT INTO chapters VALUES (223, '십만, 백만, 천만을 알아볼까요', '초등', '초4', '1학기', '', '큰 수');
INSERT INTO chapters VALUES (224, '억과 조를 알아볼까요', '초등', '초4', '1학기', '', '큰 수');
INSERT INTO chapters VALUES (225, '뛰어 세기를 해 볼까요', '초등', '초4', '1학기', '', '큰 수');
INSERT INTO chapters VALUES (226, '수의 크기를 비교해 볼까요', '초등', '초4', '1학기', '', '큰 수');
INSERT INTO chapters VALUES (227, '어느 각이 더 클까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (228, '각의 크기는 얼마일까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (229, '각을 어떻게 그릴까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (230, '직각보다 작은 각과 직각보다 큰 각을 알아볼까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (231, '각도가 얼마쯤 될까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (232, '각도의 합과 차는 얼마일까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (233, '삼각형의 세 각의 크기의 합은 얼마일까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (234, '사각형의 네 각의 크기의 합은 얼마일까요', '초등', '초4', '1학기', '', '각도');
INSERT INTO chapters VALUES (235, '세 자릿수에 몇십을 곱해 볼까요', '초등', '초4', '1학기', '', '곱셈과 나눗셈');
INSERT INTO chapters VALUES (236, '세 자릿수에 두 자릿수를 곱해 볼까요', '초등', '초4', '1학기', '', '곱셈과 나눗셈');
INSERT INTO chapters VALUES (239, '몇십 몇으로 나누어 볼까요', '초등', '초4', '1학기', '', '곱셈과 나눗셈');
INSERT INTO chapters VALUES (240, '세 자릿수를 두 자릿수로 나누어 볼까요 (1)', '초등', '초4', '1학기', '', '곱셈과 나눗셈');
INSERT INTO chapters VALUES (241, '세 자릿수를 두 자릿수로 나누어 볼까요 (2)', '초등', '초4', '1학기', '', '곱셈과 나눗셈');
INSERT INTO chapters VALUES (242, '평면도형을 밀어 볼까요', '초등', '초4', '1학기', '', '평면도형의 이동');
INSERT INTO chapters VALUES (243, '평면도형을 뒤집어 볼까요', '초등', '초4', '1학기', '', '평면도형의 이동');
INSERT INTO chapters VALUES (244, '평면도형을 돌려 볼까요', '초등', '초4', '1학기', '', '평면도형의 이동');
INSERT INTO chapters VALUES (245, '평면도형을 뒤집고 돌려 볼까요', '초등', '초4', '1학기', '', '평면도형의 이동');
INSERT INTO chapters VALUES (246, '무늬를 꾸며 볼까요', '초등', '초4', '1학기', '', '평면도형의 이동');
INSERT INTO chapters VALUES (247, '막대그래프를 알아볼까요', '초등', '초4', '1학기', '', '막대그래프');
INSERT INTO chapters VALUES (248, '막대그래프에서 무엇을 알 수 있을까요', '초등', '초4', '1학기', '', '막대그래프');
INSERT INTO chapters VALUES (249, '막대그래프를 어떻게 그릴까요', '초등', '초4', '1학기', '', '막대그래프');
INSERT INTO chapters VALUES (251, '막대그래프로 이야기를 만들어 볼까요', '초등', '초4', '1학기', '', '막대그래프');
INSERT INTO chapters VALUES (252, '수의 배열에서 규칙을 찾아볼까요', '초등', '초4', '1학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (253, '수의 배열에는 어떤 규칙이 있을까요', '초등', '초4', '1학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (254, '도형의 배열에서 규칙을 찾아볼까요', '초등', '초4', '1학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (255, '계산식에서 규칙을 찾아볼까요 (1)', '초등', '초4', '1학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (256, '계산식에서 규칙을 찾아볼까요 (2)', '초등', '초4', '1학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (257, '규칙적인 계산식은 어떻게 찾을까요', '초등', '초4', '1학기', '', '규칙 찾기');
INSERT INTO chapters VALUES (258, '분수의 덧셈을 해 볼까요 (1)', '초등', '초4', '2학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (259, '분수의 뺄셈을 해 볼까요 (1)', '초등', '초4', '2학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (260, '분수의 덧셈을 해 볼까요 (2)', '초등', '초4', '2학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (261, '분수의 뺄셈을 해 볼까요 (2)', '초등', '초4', '2학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (262, '분수의 뺄셈을 해 볼까요 (3)', '초등', '초4', '2학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (263, '분수의 뺄셈을 해 볼까요 (4)', '초등', '초4', '2학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (264, '삼각형을 분류해 볼까요 (1)', '초등', '초4', '2학기', '', '삼각형');
INSERT INTO chapters VALUES (265, '이등변삼각형의 성질을 알아볼까요', '초등', '초4', '2학기', '', '삼각형');
INSERT INTO chapters VALUES (266, '정삼각형의 성질을 알아볼까요', '초등', '초4', '2학기', '', '삼각형');
INSERT INTO chapters VALUES (267, '삼각형을 분류해 볼까요 (2)', '초등', '초4', '2학기', '', '삼각형');
INSERT INTO chapters VALUES (268, '삼각형을 두 가지 기준으로 분류해 볼까요', '초등', '초4', '2학기', '', '삼각형');
INSERT INTO chapters VALUES (269, '소수 두 자릿수를 알아볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (270, '소수 세 자릿수를 알아볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (271, '소수의 크기를 비교해 볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (272, '소수 사이의 관계를 알아볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (273, '소수 한 자릿수의 덧셈을 해 볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (274, '소수 한 자릿수의 뺄셈을 해 볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (275, '소수 두 자릿수의 덧셈을 해 볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (276, '소수 두 자릿수의 뺄셈을 해 볼까요', '초등', '초4', '2학기', '', '소수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (277, '수직을 알아볼까요', '초등', '초4', '2학기', '', '사각형');
INSERT INTO chapters VALUES (278, '평행을 알아볼까요', '초등', '초4', '2학기', '', '사각형');
INSERT INTO chapters VALUES (279, '평행선 사이의 거리를 알아볼까요', '초등', '초4', '2학기', '', '사각형');
INSERT INTO chapters VALUES (280, '사다리꼴을 알아볼까요', '초등', '초4', '2학기', '', '사각형');
INSERT INTO chapters VALUES (281, '평행사변형을 알아볼까요', '초등', '초4', '2학기', '', '사각형');
INSERT INTO chapters VALUES (282, '마름모를 알아볼까요', '초등', '초4', '2학기', '', '사각형');
INSERT INTO chapters VALUES (283, '여러 가지 사각형을 알아볼까요', '초등', '초4', '2학기', '', '사각형');
INSERT INTO chapters VALUES (284, '꺾은선그래프를 알아볼까요', '초등', '초4', '2학기', '', '꺾은선그래프');
INSERT INTO chapters VALUES (285, '꺾은선그래프에서 무엇을 알 수 있을까요', '초등', '초4', '2학기', '', '꺾은선그래프');
INSERT INTO chapters VALUES (286, '꺾은선그래프를 어떻게 그릴까요', '초등', '초4', '2학기', '', '꺾은선그래프');
INSERT INTO chapters VALUES (288, '꺾은선그래프는 어디에 쓰일까요', '초등', '초4', '2학기', '', '꺾은선그래프');
INSERT INTO chapters VALUES (289, '다각형을 알아볼까요', '초등', '초4', '2학기', '', '다각형');
INSERT INTO chapters VALUES (290, '변의 길이와 각의 크기가 모두 같은 다각형을 알아볼까요', '초등', '초4', '2학기', '', '다각형');
INSERT INTO chapters VALUES (291, '대각선을 알아볼까요', '초등', '초4', '2학기', '', '다각형');
INSERT INTO chapters VALUES (292, '모양 만들기를 해 볼까요', '초등', '초4', '2학기', '', '다각형');
INSERT INTO chapters VALUES (293, '모양 채우기를 해 볼까요', '초등', '초4', '2학기', '', '다각형');
INSERT INTO chapters VALUES (294, '덧셈과 뺄셈이 섞여 있는 식을 계산해 볼까요', '초등', '초5', '1학기', '', '자연수의 혼합 계산');
INSERT INTO chapters VALUES (295, '곱셈과 나눗셈이 섞여 있는 식을 계산해 볼까요', '초등', '초5', '1학기', '', '자연수의 혼합 계산');
INSERT INTO chapters VALUES (296, '덧셈, 뺄셈, 곱셈이 섞여 있는 식을 계산해 볼까요', '초등', '초5', '1학기', '', '자연수의 혼합 계산');
INSERT INTO chapters VALUES (297, '덧셈, 뺄셈, 나눗셈이 섞여 있는 식을 계산해 볼까요', '초등', '초5', '1학기', '', '자연수의 혼합 계산');
INSERT INTO chapters VALUES (298, '덧셈, 뺄셈, 곱셈, 나눗셈이 섞여 있는 식을 계산해 볼까요', '초등', '초5', '1학기', '', '자연수의 혼합 계산');
INSERT INTO chapters VALUES (299, '약수와 배수를 찾아볼까요', '초등', '초5', '1학기', '', '약수와 배수');
INSERT INTO chapters VALUES (301, '공약수와 최대공약수를 구해 볼까요', '초등', '초5', '1학기', '', '약수와 배수');
INSERT INTO chapters VALUES (302, '최대공약수를 구하는 방법을 알아볼까요', '초등', '초5', '1학기', '', '약수와 배수');
INSERT INTO chapters VALUES (303, '공배수와 최소공배수를 구해 볼까요', '초등', '초5', '1학기', '', '약수와 배수');
INSERT INTO chapters VALUES (304, '최소공배수를 구하는 방법을 알아볼까요', '초등', '초5', '1학기', '', '약수와 배수');
INSERT INTO chapters VALUES (305, '두 양 사이의 관계를 알아볼까요', '초등', '초5', '1학기', '', '규칙과 대응');
INSERT INTO chapters VALUES (306, '대응 관계를 식으로 나타내는 방법을 알아볼까요', '초등', '초5', '1학기', '', '규칙과 대응');
INSERT INTO chapters VALUES (307, '생활 속에서 대응 관계를 찾아 식으로 나타내어 볼까요', '초등', '초5', '1학기', '', '규칙과 대응');
INSERT INTO chapters VALUES (308, '크기가 같은 분수를 알아볼까요 (1)', '초등', '초5', '1학기', '', '약분과 통분');
INSERT INTO chapters VALUES (309, '크기가 같은 분수를 알아볼까요 (2)', '초등', '초5', '1학기', '', '약분과 통분');
INSERT INTO chapters VALUES (310, '분수를 간단하게 나타내어 볼까요', '초등', '초5', '1학기', '', '약분과 통분');
INSERT INTO chapters VALUES (311, '분모가 같은 분수로 나타내어 볼까요', '초등', '초5', '1학기', '', '약분과 통분');
INSERT INTO chapters VALUES (312, '분수의 크기를 비교해 볼까요', '초등', '초5', '1학기', '', '약분과 통분');
INSERT INTO chapters VALUES (313, '분수와 소수의 크기를 비교해 볼까요', '초등', '초5', '1학기', '', '약분과 통분');
INSERT INTO chapters VALUES (314, '분수의 덧셈을 해 볼까요 (1)', '초등', '초5', '1학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (315, '분수의 덧셈을 해 볼까요 (2)', '초등', '초5', '1학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (316, '분수의 덧셈을 해 볼까요 (3)', '초등', '초5', '1학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (317, '분수의 뺄셈을 해 볼까요 (1)', '초등', '초5', '1학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (318, '분수의 뺄셈을 해 볼까요 (2)', '초등', '초5', '1학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (319, '분수의 뺄셈을 해 볼까요 (3)', '초등', '초5', '1학기', '', '분수의 덧셈과 뺄셈');
INSERT INTO chapters VALUES (320, '정다각형의 둘레를 구해 볼까요', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (321, '사각형의 둘레를 구해 볼까요', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (322, '1cm^2 를 알아볼까요?', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (323, '직사각형의 넓이를 구해 볼까요?', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (324, '1cm^2보다 더 큰 넓이의 단위를 알아볼까요?', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (325, '평행사변형의 넓이를 구해 볼까요', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (326, '삼각형의 넓이를 구해 볼까요', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (328, '사다리꼴의 넓이를 구해 볼까요', '초등', '초5', '1학기', '', '다각형의 둘레와 넓이');
INSERT INTO chapters VALUES (329, '이상과 이하를 알아볼까요', '초등', '초5', '2학기', '', '수의 범위와 어림하기');
INSERT INTO chapters VALUES (330, '초과와 미만을 알아볼까요', '초등', '초5', '2학기', '', '수의 범위와 어림하기');
INSERT INTO chapters VALUES (331, '수의 범위를 활용하여 문제를 해결해 볼까요', '초등', '초5', '2학기', '', '수의 범위와 어림하기');
INSERT INTO chapters VALUES (332, '올림을 알아볼까요', '초등', '초5', '2학기', '', '수의 범위와 어림하기');
INSERT INTO chapters VALUES (333, '버림을 알아볼까요', '초등', '초5', '2학기', '', '수의 범위와 어림하기');
INSERT INTO chapters VALUES (334, '반올림을 알아볼까요', '초등', '초5', '2학기', '', '수의 범위와 어림하기');
INSERT INTO chapters VALUES (336, '(분수)ⅹ(자연수)를 알아볼까요', '초등', '초5', '2학기', '', '분수의 곱셈');
INSERT INTO chapters VALUES (337, '(자연수)ⅹ(분수)를 알아볼까요', '초등', '초5', '2학기', '', '분수의 곱셈');
INSERT INTO chapters VALUES (338, '진분수의 곱셈을 알아볼까요', '초등', '초5', '2학기', '', '분수의 곱셈');
INSERT INTO chapters VALUES (339, '여러 가지 분수의 곱셈을 알아볼까요', '초등', '초5', '2학기', '', '분수의 곱셈');
INSERT INTO chapters VALUES (340, '도형의 합동을 알아볼까요', '초등', '초5', '2학기', '', '합동과 대칭');
INSERT INTO chapters VALUES (341, '합동인 도형의 성질을 알아볼까요', '초등', '초5', '2학기', '', '합동과 대칭');
INSERT INTO chapters VALUES (342, '선대칭도형과 그 성질을 알아볼까요', '초등', '초5', '2학기', '', '합동과 대칭');
INSERT INTO chapters VALUES (343, '점대칭도형과 그 성질을 알아볼까요', '초등', '초5', '2학기', '', '합동과 대칭');
INSERT INTO chapters VALUES (344, '(소수)ⅹ(자연수)를 알아볼까요 (1)', '초등', '초5', '2학기', '', '소수의 곱셈');
INSERT INTO chapters VALUES (345, '(소수)ⅹ(자연수)를 알아볼까요 (2)', '초등', '초5', '2학기', '', '소수의 곱셈');
INSERT INTO chapters VALUES (346, '(자연수)ⅹ(소수)를 알아볼까요 (1)', '초등', '초5', '2학기', '', '소수의 곱셈');
INSERT INTO chapters VALUES (347, '(자연수)ⅹ(소수)를 알아볼까요 (2)', '초등', '초5', '2학기', '', '소수의 곱셈');
INSERT INTO chapters VALUES (348, '(소수)ⅹ(소수)를 알아볼까요 (3)', '초등', '초5', '2학기', '', '소수의 곱셈');
INSERT INTO chapters VALUES (349, '(소수)ⅹ(소수)를 알아볼까요 (3)', '초등', '초5', '2학기', '', '소수의 곱셈');
INSERT INTO chapters VALUES (350, '곱의 소수점 위치는 어떻게 달라질까요', '초등', '초5', '2학기', '', '소수의 곱셈');
INSERT INTO chapters VALUES (351, '직사각형 6개로 둘러싸인 도형을 알아볼까요', '초등', '초5', '2학기', '', '직육면체');
INSERT INTO chapters VALUES (352, '정사각형 6개로 둘러싸인 도형을 알아볼까요', '초등', '초5', '2학기', '', '직육면체');
INSERT INTO chapters VALUES (353, '직육면체의 성질을 알아볼까요', '초등', '초5', '2학기', '', '직육면체');
INSERT INTO chapters VALUES (354, '직육면체의 겨냥도를 알아볼까요', '초등', '초5', '2학기', '', '직육면체');
INSERT INTO chapters VALUES (355, '정육면체의 전개도를 알아볼까요', '초등', '초5', '2학기', '', '직육면체');
INSERT INTO chapters VALUES (356, '직육면체의 전개도를 알아볼까요?', '초등', '초5', '2학기', '', '직육면체');
INSERT INTO chapters VALUES (359, '평균을 구해볼까요 (2)', '초등', '초5', '2학기', '', '평균과 가능성');
INSERT INTO chapters VALUES (360, '평균을 어떻게 이용할까요', '초등', '초5', '2학기', '', '평균과 가능성');
INSERT INTO chapters VALUES (361, '일이 일어날 가능성을 말로 표현해 볼까요', '초등', '초5', '2학기', '', '평균과 가능성');
INSERT INTO chapters VALUES (362, '일이 일어날 가능성을 비교해 볼까요', '초등', '초5', '2학기', '', '평균과 가능성');
INSERT INTO chapters VALUES (363, '일이 일어날 가능성을 수로 표현해볼까요', '초등', '초5', '2학기', '', '평균과 가능성');
INSERT INTO chapters VALUES (364, '(자연수)÷(자연수)의 몫을 분수로 나타내어 볼까요 (1)', '초등', '초6', '1학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (365, '(자연수)÷(자연수)의 몫을 분수로 나타내어 볼까요 (2)', '초등', '초6', '1학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (366, '(분수)÷(자연수)를 알아볼까요', '초등', '초6', '1학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (367, '(분수)÷(자연수)를 분수의 곱셈으로 나타내어 볼까요', '초등', '초6', '1학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (368, '(대분수)÷(자연수)를 알아볼까요', '초등', '초6', '1학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (369, '각기둥을 알아볼까요 (1)', '초등', '초6', '1학기', '', '각기둥과 각뿔');
INSERT INTO chapters VALUES (370, '각기둥을 알아볼까요 (2)', '초등', '초6', '1학기', '', '각기둥과 각뿔');
INSERT INTO chapters VALUES (371, '각기둥의 전개도를 알아볼까요', '초등', '초6', '1학기', '', '각기둥과 각뿔');
INSERT INTO chapters VALUES (372, '각기둥의 전개도를 그려 볼까요', '초등', '초6', '1학기', '', '각기둥과 각뿔');
INSERT INTO chapters VALUES (373, '각뿔을 알아볼까요 (1)', '초등', '초6', '1학기', '', '각기둥과 각뿔');
INSERT INTO chapters VALUES (374, '각뿔을 알아볼까요 (2)', '초등', '초6', '1학기', '', '각기둥과 각뿔');
INSERT INTO chapters VALUES (375, '(소수)÷(자연수)를 알아볼까요 (1)', '초등', '초6', '1학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (376, '(소수)÷(자연수)를 알아볼까요 (2)', '초등', '초6', '1학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (377, '(소수)÷(자연수)를 알아볼까요 (3)', '초등', '초6', '1학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (378, '(소수)÷(자연수)를 알아볼까요 (4)', '초등', '초6', '1학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (379, '(소수)÷(자연수)를 알아볼까요 (5)', '초등', '초6', '1학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (380, '(자연수)÷(자연수)의 몫을 소수로 나타내어 볼까요', '초등', '초6', '1학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (381, '몫의 소수점 위치를 확인해 볼까요', '초등', '초6', '1학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (382, '두 수를 비교해 볼까요', '초등', '초6', '1학기', '', '비와 비율');
INSERT INTO chapters VALUES (383, '비를 알아볼까요', '초등', '초6', '1학기', '', '비와 비율');
INSERT INTO chapters VALUES (384, '비율을 알아볼까요', '초등', '초6', '1학기', '', '비와 비율');
INSERT INTO chapters VALUES (385, '비율이 사용되는 경우를 알아볼까요', '초등', '초6', '1학기', '', '비와 비율');
INSERT INTO chapters VALUES (386, '백분율을 알아볼까요', '초등', '초6', '1학기', '', '비와 비율');
INSERT INTO chapters VALUES (387, '백분율이 사용되는 경우를 알아볼까요', '초등', '초6', '1학기', '', '비와 비율');
INSERT INTO chapters VALUES (388, '그림그래프로 나타내어 볼까요', '초등', '초6', '1학기', '', '여러 가지 그래프');
INSERT INTO chapters VALUES (389, '띠그래프를 알아볼까요', '초등', '초6', '1학기', '', '여러 가지 그래프');
INSERT INTO chapters VALUES (390, '띠그래프로 나타내어 볼까요', '초등', '초6', '1학기', '', '여러 가지 그래프');
INSERT INTO chapters VALUES (391, '원그래프를 알아볼까요', '초등', '초6', '1학기', '', '여러 가지 그래프');
INSERT INTO chapters VALUES (392, '원그래프로 나타내어 볼까요', '초등', '초6', '1학기', '', '여러 가지 그래프');
INSERT INTO chapters VALUES (393, '그래프를 해석해 볼까요', '초등', '초6', '1학기', '', '여러 가지 그래프');
INSERT INTO chapters VALUES (394, '여러 가지 그래프를 비교해 볼까요', '초등', '초6', '1학기', '', '여러 가지 그래프');
INSERT INTO chapters VALUES (395, '직육면체의 부피를 비교해 볼까요', '초등', '초6', '1학기', '', '직육면체의 부피와 겉넓이');
INSERT INTO chapters VALUES (396, '직육면체의 부피를 구하는 방법을 알아볼까요', '초등', '초6', '1학기', '', '직육면체의 부피와 겉넓이');
INSERT INTO chapters VALUES (397, 'm^3를 알아볼까요', '초등', '초6', '1학기', '', '직육면체의 부피와 겉넓이');
INSERT INTO chapters VALUES (398, '직육면체의 겉넓이를 구하는 방법을 알아볼까요', '초등', '초6', '1학기', '', '직육면체의 부피와 겉넓이');
INSERT INTO chapters VALUES (399, '(분수)÷(분수)를 알아볼까요? (1)', '초등', '초6', '2학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (400, '(분수)÷(분수)를 알아볼까요 (2)', '초등', '초6', '2학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (401, '(분수)÷(분수)를 알아볼까요 (3)', '초등', '초6', '2학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (402, '(자연수)÷(분수)를 알아볼까요', '초등', '초6', '2학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (403, '(분수)÷(분수)를 (분수)ⅹ(분수)로 나타내어 볼까요', '초등', '초6', '2학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (404, '(분수)÷(분수)를 계산해 볼까요', '초등', '초6', '2학기', '', '분수의 나눗셈');
INSERT INTO chapters VALUES (405, '(소수)÷(소수)를 알아볼까요 (1)', '초등', '초6', '2학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (406, '(소수)÷(소수)를 알아볼까요 (2)', '초등', '초6', '2학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (407, '(소수)÷(소수)를 알아볼까요 (3)', '초등', '초6', '2학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (408, '(자연수)÷(소수)를 알아볼까요', '초등', '초6', '2학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (409, '몫을 반올림하여 나타내어 볼까요', '초등', '초6', '2학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (410, '나누어 주고 남는 양을 알아볼까요', '초등', '초6', '2학기', '', '소수의 나눗셈');
INSERT INTO chapters VALUES (411, '쌓은 모양과 쌓기나무의 개수를 알아볼까요 (1)', '초등', '초6', '2학기', '', '공간과 입체');
INSERT INTO chapters VALUES (412, '쌓은 모양과 쌓기나무의 개수를 알아볼까요 (2)', '초등', '초6', '2학기', '', '공간과 입체');
INSERT INTO chapters VALUES (413, '쌓은 모양과 쌓기나무의 개수를 알아볼까요 (3)', '초등', '초6', '2학기', '', '공간과 입체');
INSERT INTO chapters VALUES (414, '쌓은 모양과 쌓기나무의 개수를 알아볼까요 (4)', '초등', '초6', '2학기', '', '공간과 입체');
INSERT INTO chapters VALUES (415, '여러 가지 모양을 만들어 볼까요', '초등', '초6', '2학기', '', '공간과 입체');
INSERT INTO chapters VALUES (416, '비의 성질을 알아볼까요', '초등', '초6', '2학기', '', '비례식과 비례배분');
INSERT INTO chapters VALUES (417, '간단한 자연수의 비로 나타내어 볼까요', '초등', '초6', '2학기', '', '비례식과 비례배분');
INSERT INTO chapters VALUES (418, '비례식을 알아볼까요', '초등', '초6', '2학기', '', '비례식과 비례배분');
INSERT INTO chapters VALUES (420, '비례식을 활용해 볼까요', '초등', '초6', '2학기', '', '비례식과 비례배분');
INSERT INTO chapters VALUES (421, '비례배분을 해볼까요', '초등', '초6', '2학기', '', '비례식과 비례배분');
INSERT INTO chapters VALUES (422, '원주와 지름의 관계를 알아볼까요', '초등', '초6', '2학기', '', '원의 넓이');
INSERT INTO chapters VALUES (423, '원주율을 알아볼까요', '초등', '초6', '2학기', '', '원의 넓이');
INSERT INTO chapters VALUES (424, '원주와 지름을 구해 볼까요', '초등', '초6', '2학기', '', '원의 넓이');
INSERT INTO chapters VALUES (425, '원의 넓이를 어림해 볼까요', '초등', '초6', '2학기', '', '원의 넓이');
INSERT INTO chapters VALUES (426, '원의 넓이를 구하는 방법을 알아볼까요', '초등', '초6', '2학기', '', '원의 넓이');
INSERT INTO chapters VALUES (427, '여러 가지 원의 넓이를 구해 볼까요', '초등', '초6', '2학기', '', '원의 넓이');
INSERT INTO chapters VALUES (428, '원기둥을 알아볼까요', '초등', '초6', '2학기', '', '원기둥, 원뿔, 구');
INSERT INTO chapters VALUES (429, '원기둥의 전개도를 알아볼까요', '초등', '초6', '2학기', '', '원기둥, 원뿔, 구');
INSERT INTO chapters VALUES (430, '원뿔을 알아볼까요', '초등', '초6', '2학기', '', '원기둥, 원뿔, 구');
INSERT INTO chapters VALUES (431, '구를 알아볼까요', '초등', '초6', '2학기', '', '원기둥, 원뿔, 구');
INSERT INTO chapters VALUES (434, '소인수분해', '중등', '중1', '1학기', '수와 연산', '소인수분해');
INSERT INTO chapters VALUES (435, '최대공약수', '중등', '중1', '1학기', '수와 연산', '소인수분해');
INSERT INTO chapters VALUES (436, '최소공배수', '중등', '중1', '1학기', '수와 연산', '소인수분해');
INSERT INTO chapters VALUES (437, '정수와 유리수', '중등', '중1', '1학기', '수와 연산', '정수와유리수');
INSERT INTO chapters VALUES (438, '정수와 유리수의 대소관계', '중등', '중1', '1학기', '수와 연산', '정수와유리수');
INSERT INTO chapters VALUES (439, '정수와 유리수의 덧셈', '중등', '중1', '1학기', '수와 연산', '정수와유리수');
INSERT INTO chapters VALUES (440, '정수와 유리수의 곱셈', '중등', '중1', '1학기', '수와 연산', '정수와유리수');
INSERT INTO chapters VALUES (441, '정수와 유리수의 나눗셈', '중등', '중1', '1학기', '수와 연산', '정수와유리수');
INSERT INTO chapters VALUES (442, '문자를 사용한 식', '중등', '중1', '1학기', '문자와식', '문자의 사용과 식의 계산');
INSERT INTO chapters VALUES (443, '식의 값', '중등', '중1', '1학기', '문자와식', '문자의 사용과 식의 계산');
INSERT INTO chapters VALUES (444, '일차식', '중등', '중1', '1학기', '문자와식', '문자의 사용과 식의 계산');
INSERT INTO chapters VALUES (445, '일차식과 계산', '중등', '중1', '1학기', '문자와식', '문자의 사용과 식의 계산');
INSERT INTO chapters VALUES (446, '일차방정식의 해', '중등', '중1', '1학기', '문자와식', '일차방정식');
INSERT INTO chapters VALUES (447, '등식의 성질', '중등', '중1', '1학기', '문자와식', '일차방정식');
INSERT INTO chapters VALUES (448, '일차방정식의 풀이', '중등', '중1', '1학기', '문자와식', '일차방정식');
INSERT INTO chapters VALUES (449, '순서쌍과 좌표', '중등', '중1', '1학기', '좌표평면과 그래프', '좌표평면과 그래프');
INSERT INTO chapters VALUES (450, '그래프의 해석', '중등', '중1', '1학기', '좌표평면과 그래프', '좌표평면과 그래프');
INSERT INTO chapters VALUES (451, '정비례', '중등', '중1', '1학기', '좌표평면과 그래프', '정비례와 반비례');
INSERT INTO chapters VALUES (452, '반비례', '중등', '중1', '1학기', '좌표평면과 그래프', '정비례와 반비례');
INSERT INTO chapters VALUES (453, '점, 선, 면', '중등', '중1', '2학기', '기본도형', '기본도형');
INSERT INTO chapters VALUES (454, '각의 성질', '중등', '중1', '2학기', '기본도형', '기본도형');
INSERT INTO chapters VALUES (455, '점, 직선, 평면의 위치 관계', '중등', '중1', '2학기', '기본도형', '기본도형');
INSERT INTO chapters VALUES (456, '평행선의 성질', '중등', '중1', '2학기', '기본도형', '기본도형');
INSERT INTO chapters VALUES (457, '간단한 도형의 작도', '중등', '중1', '2학기', '기본도형', '작도와 합동');
INSERT INTO chapters VALUES (458, '삼각형의 작도', '중등', '중1', '2학기', '기본도형', '작도와 합동');
INSERT INTO chapters VALUES (459, '삼각형의 합동', '중등', '중1', '2학기', '기본도형', '작도와 합동');
INSERT INTO chapters VALUES (460, '다각형의 대각선의 개수', '중등', '중1', '2학기', '평면도형과 입체도형', '평면도형의 성질');
INSERT INTO chapters VALUES (461, '삼각형의 내각과 외각', '중등', '중1', '2학기', '평면도형과 입체도형', '평면도형의 성질');
INSERT INTO chapters VALUES (462, '다각형의 내각의 크기의 합', '중등', '중1', '2학기', '평면도형과 입체도형', '평면도형의 성질');
INSERT INTO chapters VALUES (463, '다각형의 외각의 크기의 합', '중등', '중1', '2학기', '평면도형과 입체도형', '평면도형의 성질');
INSERT INTO chapters VALUES (464, '원과 부채꼴', '중등', '중1', '2학기', '평면도형과 입체도형', '평면도형의 성질');
INSERT INTO chapters VALUES (465, '부채꼴의 호의 길이와 넓이', '중등', '중1', '2학기', '평면도형과 입체도형', '평면도형의 성질');
INSERT INTO chapters VALUES (466, '다면체', '중등', '중1', '2학기', '평면도형과 입체도형', '입체도형의 성질');
INSERT INTO chapters VALUES (467, '회전체', '중등', '중1', '2학기', '평면도형과 입체도형', '입체도형의 성질');
INSERT INTO chapters VALUES (468, '기둥의 겉넓이', '중등', '중1', '2학기', '평면도형과 입체도형', '입체도형의 성질');
INSERT INTO chapters VALUES (469, '기둥의 부피', '중등', '중1', '2학기', '평면도형과 입체도형', '입체도형의 성질');
INSERT INTO chapters VALUES (470, '뿔의 겉넓이', '중등', '중1', '2학기', '평면도형과 입체도형', '입체도형의 성질');
INSERT INTO chapters VALUES (471, '뿔의 부피', '중등', '중1', '2학기', '평면도형과 입체도형', '입체도형의 성질');
INSERT INTO chapters VALUES (472, '구의 겉넓이와 부피', '중등', '중1', '2학기', '평면도형과 입체도형', '입체도형의 성질');
INSERT INTO chapters VALUES (473, '줄기와 잎 그림', '중등', '중1', '2학기', '통계', '자료의 정리와 해석');
INSERT INTO chapters VALUES (474, '도수분포표', '중등', '중1', '2학기', '통계', '자료의 정리와 해석');
INSERT INTO chapters VALUES (475, '히스토그램과 도수분포다각형', '중등', '중1', '2학기', '통계', '자료의 정리와 해석');
INSERT INTO chapters VALUES (476, '상대도수와 그래프', '중등', '중1', '2학기', '통계', '자료의 정리와 해석');
INSERT INTO chapters VALUES (477, '실생활 자료의 정리와 해석', '중등', '중1', '2학기', '통계', '자료의 정리와 해석');
INSERT INTO chapters VALUES (478, '순환소수', '중등', '중2', '1학기', '유리수와 소수', '유리수와 소수');
INSERT INTO chapters VALUES (480, '순환소수의 분수 표현', '중등', '중2', '1학기', '유리수와 소수', '유리수와 소수');
INSERT INTO chapters VALUES (481, '지수법칙', '중등', '중2', '1학기', '식의 계산', '단항식의 계산');
INSERT INTO chapters VALUES (482, '단항식의 곱셈과 나눗셈', '중등', '중2', '1학기', '식의 계산', '단항식의 계산');
INSERT INTO chapters VALUES (483, '다항식의 덧셈과 뺄셈', '중등', '중2', '1학기', '식의 계산', '다항식의 계산');
INSERT INTO chapters VALUES (484, '다항식의 곱셈과 나눗셈', '중등', '중2', '1학기', '식의 계산', '다항식의 계산');
INSERT INTO chapters VALUES (485, '부등식의 해', '중등', '중2', '1학기', '일차방부등식과 연립일차방정식', '일차부등식');
INSERT INTO chapters VALUES (486, '부등식의 성질', '중등', '중2', '1학기', '일차방부등식과 연립일차방정식', '일차부등식');
INSERT INTO chapters VALUES (487, '일차부등식의 풀이', '중등', '중2', '1학기', '일차방부등식과 연립일차방정식', '일차부등식');
INSERT INTO chapters VALUES (488, '미지수가 2개인 일차방정식', '중등', '중2', '1학기', '일차방부등식과 연립일차방정식', '연립일차방정식');
INSERT INTO chapters VALUES (489, '미지수가 2개인 연립일차방정식', '중등', '중2', '1학기', '일차방부등식과 연립일차방정식', '연립일차방정식');
INSERT INTO chapters VALUES (490, '연립일차방정식의 풀이', '중등', '중2', '1학기', '일차방부등식과 연립일차방정식', '연립일차방정식');
INSERT INTO chapters VALUES (491, '함수의 뜻', '중등', '중2', '1학기', '함수', '일차함수와 그래프');
INSERT INTO chapters VALUES (492, '일차함수의 뜻과 그래프', '중등', '중2', '1학기', '함수', '일차함수와 그래프');
INSERT INTO chapters VALUES (493, '일차함수의 그래프의 성질', '중등', '중2', '1학기', '함수', '일차함수와 그래프');
INSERT INTO chapters VALUES (494, '일차함수와 일차방정식', '중등', '중2', '1학기', '함수', '일차함수와 일차방정식의 관계');
INSERT INTO chapters VALUES (495, '일차함수의 그래프와 연립일차방정식의 해', '중등', '중2', '1학기', '함수', '일차함수와 일차방정식의 관계');
INSERT INTO chapters VALUES (496, '이등변삼각형의 성질', '중등', '중2', '2학기', '도형의 성질', '삼각형의 성질');
INSERT INTO chapters VALUES (497, '직각삼각형의 합동조건', '중등', '중2', '2학기', '도형의 성질', '삼각형의 성질');
INSERT INTO chapters VALUES (498, '삼각형의 외심과 내심', '중등', '중2', '2학기', '도형의 성질', '삼각형의 성질');
INSERT INTO chapters VALUES (499, '평행사변형', '중등', '중2', '2학기', '도형의 성질', '사각형의 성질');
INSERT INTO chapters VALUES (500, '여러가지 사각형', '중등', '중2', '2학기', '도형의 성질', '사각형의 성질');
INSERT INTO chapters VALUES (501, '도형의 닮음', '중등', '중2', '2학기', '도형의 닮음', '도형의 닮음');
INSERT INTO chapters VALUES (502, '삼각형의 닮음 조건', '중등', '중2', '2학기', '도형의 닮음', '도형의 닮음');
INSERT INTO chapters VALUES (503, '평행선 사이의 선분의 길이의 비', '중등', '중2', '2학기', '도형의 닮음', '닮음의 응용');
INSERT INTO chapters VALUES (504, '삼각형의 무게중심', '중등', '중2', '2학기', '도형의 닮음', '닮음의 응용');
INSERT INTO chapters VALUES (505, '닮은 도형의 넓이와 부피', '중등', '중2', '2학기', '도형의 닮음', '닮음의 응용');
INSERT INTO chapters VALUES (506, '피타고라스 정리', '중등', '중2', '2학기', '피타고라스 정리', '피타고라스 정리');
INSERT INTO chapters VALUES (507, '사건과 경우의 수', '중등', '중2', '2학기', '확률', '경우의 수');
INSERT INTO chapters VALUES (508, '확률의 기본성질', '중등', '중2', '2학기', '확률', '확률의 계산');
INSERT INTO chapters VALUES (509, '확률의 계산', '중등', '중2', '2학기', '확률', '확률의 계산');
INSERT INTO chapters VALUES (510, '제곱근의 뜻', '중등', '중3', '1학기', '제곱근과 실수', '제곱근과 실수');
INSERT INTO chapters VALUES (511, '제곱근의 성질', '중등', '중3', '1학기', '제곱근과 실수', '제곱근과 실수');
INSERT INTO chapters VALUES (512, '무리수와 실수', '중등', '중3', '1학기', '제곱근과 실수', '제곱근과 실수');
INSERT INTO chapters VALUES (513, '실수의 대소 관계', '중등', '중3', '1학기', '제곱근과 실수', '제곱근과 실수');
INSERT INTO chapters VALUES (514, '근호를 포함한 식의 곱셈과 나눗셈', '중등', '중3', '1학기', '제곱근과 실수', '근호를 포함한 식의 계산');
INSERT INTO chapters VALUES (515, '근호를 포함한 식의 덧셈과 뺄셈', '중등', '중3', '1학기', '제곱근과 실수', '근호를 포함한 식의 계산');
INSERT INTO chapters VALUES (516, '다항식의 곱셈', '중등', '중3', '1학기', '다항식의 곱셈과 인수분해', '다항식의 곱셈');
INSERT INTO chapters VALUES (517, '다항식의 인수분해', '중등', '중3', '1학기', '다항식의 곱셈과 인수분해', '다항식의 인수분해');
INSERT INTO chapters VALUES (518, '인수분해 공식', '중등', '중3', '1학기', '다항식의 곱셈과 인수분해', '다항식의 인수분해');
INSERT INTO chapters VALUES (519, '이차방정식의 뜻', '중등', '중3', '1학기', '이차방정식', '이차방정식');
INSERT INTO chapters VALUES (520, '인수분해를 이용한 이차방정식의 풀이', '중등', '중3', '1학기', '이차방정식', '이차방정식');
INSERT INTO chapters VALUES (521, '제곱근을 이용한 이차방정식의 풀이', '중등', '중3', '1학기', '이차방정식', '이차방정식');
INSERT INTO chapters VALUES (522, '근의 공식을 이용한 이차방정식의 풀이', '중등', '중3', '1학기', '이차방정식', '이차방정식');
INSERT INTO chapters VALUES (523, '이차함수의 뜻', '중등', '중3', '1학기', '이차함수', '이차함수와 그래프');
INSERT INTO chapters VALUES (524, '이차함수 y=ax^2의 그래프', '중등', '중3', '1학기', '이차함수', '이차함수와 그래프');
INSERT INTO chapters VALUES (525, '이차함수 y=a(x-p)^2+q의 그래프', '중등', '중3', '1학기', '이차함수', '이차함수와 그래프');
INSERT INTO chapters VALUES (526, '이차함수 y=ax^2+bx+c의 그래프', '중등', '중3', '1학기', '이차함수', '이차함수와 그래프');
INSERT INTO chapters VALUES (527, '삼각비', '중등', '중3', '2학기', '삼각비', '삼각비');
INSERT INTO chapters VALUES (528, '삼각비의 값', '중등', '중3', '2학기', '삼각비', '삼각비');
INSERT INTO chapters VALUES (529, '삼각비의 길이 구하기', '중등', '중3', '2학기', '삼각비', '삼각비');
INSERT INTO chapters VALUES (530, '삼각비의 넓이 구하기', '중등', '중3', '2학기', '삼각비', '삼각비');
INSERT INTO chapters VALUES (531, '원의 현', '중등', '중3', '2학기', '원의 성질', '원과 직선');
INSERT INTO chapters VALUES (532, '원의 접선', '중등', '중3', '2학기', '원의 성질', '원과 직선');
INSERT INTO chapters VALUES (533, '원주각과 그 성질', '중등', '중3', '2학기', '원의 성질', '원주각');
INSERT INTO chapters VALUES (534, '원의 접선과 현이 이루는 각', '중등', '중3', '2학기', '원의 성질', '원주각');
INSERT INTO chapters VALUES (535, '대푯값', '중등', '중3', '2학기', '통계', '대푯값과 산포도');
INSERT INTO chapters VALUES (538, '여러 가지 상관관계', '중등', '중3', '2학기', '통계', '상관관계');
INSERT INTO chapters VALUES (539, '다항식의 덧셈과 뺄셈', '고등', '수학', '상', '다항식', '다항식의 연산');
INSERT INTO chapters VALUES (540, '다항식의 곱셈', '고등', '수학', '상', '다항식', '다항식의 연산');
INSERT INTO chapters VALUES (541, '다항식의 나눗셈', '고등', '수학', '상', '다항식', '다항식의 연산');
INSERT INTO chapters VALUES (542, '항등식', '고등', '수학', '상', '다항식', '나머지정리와 인수분해');
INSERT INTO chapters VALUES (543, '나머지정리', '고등', '수학', '상', '다항식', '나머지정리와 인수분해');
INSERT INTO chapters VALUES (544, '인수정리', '고등', '수학', '상', '다항식', '나머지정리와 인수분해');
INSERT INTO chapters VALUES (545, '인수분해', '고등', '수학', '상', '다항식', '나머지정리와 인수분해');
INSERT INTO chapters VALUES (546, '복소수', '고등', '수학', '상', '방정식과 부등식', '복소수와 이차방정식');
INSERT INTO chapters VALUES (547, '복소수의 사칙연산', '고등', '수학', '상', '방정식과 부등식', '복소수와 이차방정식');
INSERT INTO chapters VALUES (548, '이차방정식의 판별식', '고등', '수학', '상', '방정식과 부등식', '복소수와 이차방정식');
INSERT INTO chapters VALUES (549, '이차방정식의 근과 계수의 관계', '고등', '수학', '상', '방정식과 부등식', '복소수와 이차방정식');
INSERT INTO chapters VALUES (550, '이차방정식과 이차함수의 관계', '고등', '수학', '상', '방정식과 부등식', '이차방정식과 이차함수');
INSERT INTO chapters VALUES (551, '이차함수의 그래프와 직선의 위치 관계', '고등', '수학', '상', '방정식과 부등식', '이차방정식과 이차함수');
INSERT INTO chapters VALUES (552, '이차함수의 최대, 최소', '고등', '수학', '상', '방정식과 부등식', '이차방정식과 이차함수');
INSERT INTO chapters VALUES (553, '삼차방정식과 사차방정식', '고등', '수학', '상', '방정식과 부등식', '여러가지 방정식');
INSERT INTO chapters VALUES (554, '연립이차방정식', '고등', '수학', '상', '방정식과 부등식', '여러가지 방정식');
INSERT INTO chapters VALUES (555, '연립일차부등식', '고등', '수학', '상', '방정식과 부등식', '여러가지 부등식');
INSERT INTO chapters VALUES (556, '절댓값을 포함한 일차부등식', '고등', '수학', '상', '방정식과 부등식', '여러가지 부등식');
INSERT INTO chapters VALUES (557, '이차부등식', '고등', '수학', '상', '방정식과 부등식', '여러가지 부등식');
INSERT INTO chapters VALUES (558, '두 점 사이의 거리', '고등', '수학', '상', '도형의 방정식', '평면좌표');
INSERT INTO chapters VALUES (559, '선분의 내분과 외분', '고등', '수학', '상', '도형의 방정식', '평면좌표');
INSERT INTO chapters VALUES (560, '직선의 방정식', '고등', '수학', '상', '도형의 방정식', '직선의 방정식');
INSERT INTO chapters VALUES (561, '두 직선의 평행과 수직', '고등', '수학', '상', '도형의 방정식', '직선의 방정식');
INSERT INTO chapters VALUES (562, '점과 직선 사이의 거리', '고등', '수학', '상', '도형의 방정식', '직선의 방정식');
INSERT INTO chapters VALUES (563, '원의 방정식', '고등', '수학', '상', '도형의 방정식', '원의 방정식');
INSERT INTO chapters VALUES (564, '원과 직선의 위치 관계', '고등', '수학', '상', '도형의 방정식', '원의 방정식');
INSERT INTO chapters VALUES (565, '평행이동', '고등', '수학', '상', '도형의 방정식', '도형의 이동');
INSERT INTO chapters VALUES (566, '대칭이동', '고등', '수학', '상', '도형의 방정식', '도형의 이동');
INSERT INTO chapters VALUES (567, '집합의 개념과 표현', '고등', '수학', '하', '집합과 명제', '집합');
INSERT INTO chapters VALUES (568, '집합 사이의 포함 관계', '고등', '수학', '하', '집합과 명제', '집합');
INSERT INTO chapters VALUES (569, '합집합과 교집합', '고등', '수학', '하', '집합과 명제', '집합');
INSERT INTO chapters VALUES (570, '여집합과 차집합', '고등', '수학', '하', '집합과 명제', '집합');
INSERT INTO chapters VALUES (571, '명제와 조건', '고등', '수학', '하', '집합과 명제', '명제');
INSERT INTO chapters VALUES (572, '명제의 역과 대우', '고등', '수학', '하', '집합과 명제', '명제');
INSERT INTO chapters VALUES (573, '충분조건과 필요조건', '고등', '수학', '하', '집합과 명제', '명제');
INSERT INTO chapters VALUES (575, '절대부등식', '고등', '수학', '하', '집합과 명제', '명제');
INSERT INTO chapters VALUES (576, '함수의 뜻과 그래프', '고등', '수학', '하', '함수', '함수');
INSERT INTO chapters VALUES (577, '여러가지 함수', '고등', '수학', '하', '함수', '함수');
INSERT INTO chapters VALUES (578, '합성함수', '고등', '수학', '하', '함수', '함수');
INSERT INTO chapters VALUES (579, '역함수', '고등', '수학', '하', '함수', '함수');
INSERT INTO chapters VALUES (580, '유리식과 유리함수', '고등', '수학', '하', '함수', '유리함수와 무리함수');
INSERT INTO chapters VALUES (581, '유리함수의 그래프', '고등', '수학', '하', '함수', '유리함수와 무리함수');
INSERT INTO chapters VALUES (582, '무리식과 무리함수', '고등', '수학', '하', '함수', '유리함수와 무리함수');
INSERT INTO chapters VALUES (585, '순열', '고등', '수학', '하', '경우의 수', '순열과 조합');
INSERT INTO chapters VALUES (586, '조합', '고등', '수학', '하', '경우의 수', '순열과 조합');
INSERT INTO chapters VALUES (587, '거듭제곱과 거듭제곱근', '고등', '수1', '전체', '지수함수와 로그함수', '지수');
INSERT INTO chapters VALUES (588, '지수의 확장과 지수법칙', '고등', '수1', '전체', '지수함수와 로그함수', '지수');
INSERT INTO chapters VALUES (589, '로그의 뜻과 성질', '고등', '수1', '전체', '지수함수와 로그함수', '로그');
INSERT INTO chapters VALUES (590, '상용로그', '고등', '수1', '전체', '지수함수와 로그함수', '로그');
INSERT INTO chapters VALUES (591, '지수함수와 그 그래프', '고등', '수1', '전체', '지수함수와 로그함수', '지수함수와 로그함수');
INSERT INTO chapters VALUES (592, '로그함수와 그 그래프', '고등', '수1', '전체', '지수함수와 로그함수', '지수함수와 로그함수');
INSERT INTO chapters VALUES (594, '로그함수의 활용', '고등', '수1', '전체', '지수함수와 로그함수', '지수함수와 로그함수');
INSERT INTO chapters VALUES (595, '일반각과 호도법', '고등', '수1', '전체', '삼각함수', '삼각함수의 뜻과 그래프');
INSERT INTO chapters VALUES (596, '삼각함수의 뜻', '고등', '수1', '전체', '삼각함수', '삼각함수의 뜻과 그래프');
INSERT INTO chapters VALUES (597, '삼각함수의 그래프와 성질', '고등', '수1', '전체', '삼각함수', '삼각함수의 뜻과 그래프');
INSERT INTO chapters VALUES (598, '사인법칙', '고등', '수1', '전체', '삼각함수', '사인법칙과 코사인법칙');
INSERT INTO chapters VALUES (599, '코사인법칙', '고등', '수1', '전체', '삼각함수', '사인법칙과 코사인법칙');
INSERT INTO chapters VALUES (600, '삼각형의 넓이', '고등', '수1', '전체', '삼각함수', '사인법칙과 코사인법칙');
INSERT INTO chapters VALUES (601, '수열의 뜻', '고등', '수1', '전체', '수열', '등차수열과 등비수열');
INSERT INTO chapters VALUES (602, '등차수열', '고등', '수1', '전체', '수열', '등차수열과 등비수열');
INSERT INTO chapters VALUES (603, '등비수열', '고등', '수1', '전체', '수열', '등차수열과 등비수열');
INSERT INTO chapters VALUES (604, '기호 ∑의 뜻과 성질', '고등', '수1', '전체', '수열', '수열의 합');
INSERT INTO chapters VALUES (605, '여러 가지 수열의 합', '고등', '수1', '전체', '수열', '수열의 합');
INSERT INTO chapters VALUES (606, '수열의 귀납적 정의', '고등', '수1', '전체', '수열', '수학적 귀납법');
INSERT INTO chapters VALUES (607, '수학적 귀납법', '고등', '수1', '전체', '수열', '수학적 귀납법');
INSERT INTO chapters VALUES (608, '함수의 극한의 뜻', '고등', '수2', '전체', '함수의 극한과 연속', '함수의 극한');
INSERT INTO chapters VALUES (609, '함수의 극한의 성질', '고등', '수2', '전체', '함수의 극한과 연속', '함수의 극한');
INSERT INTO chapters VALUES (610, '연속함수', '고등', '수2', '전체', '함수의 극한과 연속', '함수의 연속');
INSERT INTO chapters VALUES (611, '연속함수의 성질', '고등', '수2', '전체', '함수의 극한과 연속', '함수의 연속');
INSERT INTO chapters VALUES (612, '미분계수', '고등', '수2', '전체', '다항함수의 미분법', '미분계수와 도함수');
INSERT INTO chapters VALUES (613, '미분가능성과 연속성', '고등', '수2', '전체', '다항함수의 미분법', '미분계수와 도함수');
INSERT INTO chapters VALUES (614, '도함수', '고등', '수2', '전체', '다항함수의 미분법', '미분계수와 도함수');
INSERT INTO chapters VALUES (615, '접선의 방정식', '고등', '수2', '전체', '다항함수의 미분법', '도함수의 활용');
INSERT INTO chapters VALUES (616, '평균값 정리', '고등', '수2', '전체', '다항함수의 미분법', '도함수의 활용');
INSERT INTO chapters VALUES (617, '함수의 증가와 감소, 극대와 극소', '고등', '수2', '전체', '다항함수의 미분법', '도함수의 활용');
INSERT INTO chapters VALUES (618, '함수의 그래프와 그 활용', '고등', '수2', '전체', '다항함수의 미분법', '도함수의 활용');
INSERT INTO chapters VALUES (619, '속도와 가속도', '고등', '수2', '전체', '다항함수의 미분법', '도함수의 활용');
INSERT INTO chapters VALUES (620, '부정적분', '고등', '수2', '전체', '다항함수의 적분법', '부정적분');
INSERT INTO chapters VALUES (621, '부정적분의 계산', '고등', '수2', '전체', '다항함수의 적분법', '부정적분');
INSERT INTO chapters VALUES (622, '정적분', '고등', '수2', '전체', '다항함수의 적분법', '정적분');
INSERT INTO chapters VALUES (623, '정적분의 성질', '고등', '수2', '전체', '다항함수의 적분법', '정적분');
INSERT INTO chapters VALUES (624, '넓이', '고등', '수2', '전체', '다항함수의 적분법', '정적분의 활용');
INSERT INTO chapters VALUES (625, '속도와 거리', '고등', '수2', '전체', '다항함수의 적분법', '정적분의 활용');
INSERT INTO chapters VALUES (626, '여러 가지 순열', '고등', '확통', '전체', '경우의 수', '순열과 조합');
INSERT INTO chapters VALUES (627, '중복조합', '고등', '확통', '전체', '경우의 수', '순열과 조합');
INSERT INTO chapters VALUES (628, '이항정리', '고등', '확통', '전체', '경우의 수', '이항정리');
INSERT INTO chapters VALUES (629, '확률의 뜻과 기본 성질', '고등', '확통', '전체', '확률', '확률의 뜻과 활용');
INSERT INTO chapters VALUES (630, '확률의 덧셈정리', '고등', '확통', '전체', '확률', '확률의 뜻과 활용');
INSERT INTO chapters VALUES (631, '조건부 확률', '고등', '확통', '전체', '확률', '조건부 확률');
INSERT INTO chapters VALUES (632, '사건의 독립과 종속', '고등', '확통', '전체', '확률', '조건부 확률');
INSERT INTO chapters VALUES (633, '이산확률변수와 확률분포', '고등', '확통', '전체', '통계', '확률분포');
INSERT INTO chapters VALUES (634, '이항분포', '고등', '확통', '전체', '통계', '확률분포');
INSERT INTO chapters VALUES (635, '연속확률변수와 확률분포', '고등', '확통', '전체', '통계', '확률분포');
INSERT INTO chapters VALUES (636, '정규분포', '고등', '확통', '전체', '통계', '확률분포');
INSERT INTO chapters VALUES (637, '모집단과 표본', '고등', '확통', '전체', '통계', '통계적 추정');
INSERT INTO chapters VALUES (638, '모평균의 추정', '고등', '확통', '전체', '통계', '통계적 추정');
INSERT INTO chapters VALUES (639, '수열의 극한', '고등', '미적', '전체', '수열의 극한', '수열의극한');
INSERT INTO chapters VALUES (640, '수열의 극한에 대한 기본 성질', '고등', '미적', '전체', '수열의 극한', '수열의극한');
INSERT INTO chapters VALUES (641, '등비수열의 극한', '고등', '미적', '전체', '수열의 극한', '수열의극한');
INSERT INTO chapters VALUES (642, '급수', '고등', '미적', '전체', '수열의 극한', '급수');
INSERT INTO chapters VALUES (643, '등비급수', '고등', '미적', '전체', '수열의 극한', '급수');
INSERT INTO chapters VALUES (644, '등비급수의 활용', '고등', '미적', '전체', '수열의 극한', '급수');
INSERT INTO chapters VALUES (645, '지수함수와 로그함수의 극한', '고등', '미적', '전체', '미분법', '여러 가지 함수의 미분');
INSERT INTO chapters VALUES (646, '지수함수와 로그함수의 미분', '고등', '미적', '전체', '미분법', '여러 가지 함수의 미분');
INSERT INTO chapters VALUES (647, '삼각함수의 덧셈정리', '고등', '미적', '전체', '미분법', '여러 가지 함수의 미분');
INSERT INTO chapters VALUES (648, '삼각함수의 극한', '고등', '미적', '전체', '미분법', '여러 가지 함수의 미분');
INSERT INTO chapters VALUES (649, '삼각함수의 미분', '고등', '미적', '전체', '미분법', '여러 가지 함수의 미분');
INSERT INTO chapters VALUES (650, '함수의 몫의 미분법', '고등', '미적', '전체', '미분법', '여러 가지 미분법');
INSERT INTO chapters VALUES (651, '합성함수의 미분법', '고등', '미적', '전체', '미분법', '여러 가지 미분법');
INSERT INTO chapters VALUES (652, '매개변수로 나타낸 함수의 미분법', '고등', '미적', '전체', '미분법', '여러 가지 미분법');
INSERT INTO chapters VALUES (653, '음함수와 역함수의 미분법', '고등', '미적', '전체', '미분법', '여러 가지 미분법');
INSERT INTO chapters VALUES (654, '이계도 함수', '고등', '미적', '전체', '미분법', '여러 가지 미분법');
INSERT INTO chapters VALUES (655, '접선의 방정식', '고등', '미적', '전체', '미분법', '도함수의 활용');
INSERT INTO chapters VALUES (656, '함수의 그래프', '고등', '미적', '전체', '미분법', '도함수의 활용');
INSERT INTO chapters VALUES (657, '방정식과 부등식에의 활용', '고등', '미적', '전체', '미분법', '도함수의 활용');
INSERT INTO chapters VALUES (658, '속도와 가속도', '고등', '미적', '전체', '미분법', '도함수의 활용');
INSERT INTO chapters VALUES (659, '여러 가지 함수의 부정적분', '고등', '미적', '전체', '적분법', '여러 가지 적분법');
INSERT INTO chapters VALUES (660, '치환적분법', '고등', '미적', '전체', '적분법', '여러 가지 적분법');
INSERT INTO chapters VALUES (661, '부분적분법', '고등', '미적', '전체', '적분법', '여러 가지 적분법');
INSERT INTO chapters VALUES (662, '여러 가지 함수의 정적분', '고등', '미적', '전체', '적분법', '여러 가지 적분법');
INSERT INTO chapters VALUES (663, '정적분과 급수와의 관계', '고등', '미적', '전체', '적분법', '정적분의 활용');
INSERT INTO chapters VALUES (664, '넓이', '고등', '미적', '전체', '적분법', '정적분의 활용');
INSERT INTO chapters VALUES (665, '부피', '고등', '미적', '전체', '적분법', '정적분의 활용');
INSERT INTO chapters VALUES (666, '속도와 거리', '고등', '미적', '전체', '적분법', '정적분의 활용');
INSERT INTO chapters VALUES (667, '포물선', '고등', '기하', '전체', '이차곡선', '이차곡선');
INSERT INTO chapters VALUES (668, '타원', '고등', '기하', '전체', '이차곡선', '이차곡선');
INSERT INTO chapters VALUES (669, '쌍곡선', '고등', '기하', '전체', '이차곡선', '이차곡선');
INSERT INTO chapters VALUES (670, '포물선과 직선', '고등', '기하', '전체', '이차곡선', '이차곡선과 직선');
INSERT INTO chapters VALUES (671, '타원과 직선', '고등', '기하', '전체', '이차곡선', '이차곡선과 직선');
INSERT INTO chapters VALUES (672, '쌍곡선과 직선', '고등', '기하', '전체', '이차곡선', '이차곡선과 직선');
INSERT INTO chapters VALUES (673, '벡터', '고등', '기하', '전체', '벡터', '벡터의 연산');
INSERT INTO chapters VALUES (674, '벡터의 덧셈과 뺄셈', '고등', '기하', '전체', '벡터', '벡터의 연산');
INSERT INTO chapters VALUES (675, '벡터의 실수배', '고등', '기하', '전체', '벡터', '벡터의 연산');
INSERT INTO chapters VALUES (676, '위치벡터', '고등', '기하', '전체', '벡터', '평면벡터의 성분과 내적');
INSERT INTO chapters VALUES (677, '평면벡터의 성분', '고등', '기하', '전체', '벡터', '평면벡터의 성분과 내적');
INSERT INTO chapters VALUES (678, '평면벡터의 내적', '고등', '기하', '전체', '벡터', '평면벡터의 성분과 내적');
INSERT INTO chapters VALUES (679, '직선과 원의 방정식', '고등', '기하', '전체', '벡터', '평면벡터의 성분과 내적');
INSERT INTO chapters VALUES (680, '위치관계', '고등', '기하', '전체', '공간도형', '공간도형');
INSERT INTO chapters VALUES (681, '삼수선의 정리', '고등', '기하', '전체', '공간도형', '공간도형');
INSERT INTO chapters VALUES (682, '정사영', '고등', '기하', '전체', '공간도형', '공간도형');
INSERT INTO chapters VALUES (683, '점의 좌표', '고등', '기하', '전체', '공간도형', '공간좌표');
INSERT INTO chapters VALUES (684, '두 점 사이의 거리', '고등', '기하', '전체', '공간도형', '공간좌표');
INSERT INTO chapters VALUES (685, '선분의 내분점과 외분점', '고등', '기하', '전체', '공간도형', '공간좌표');
INSERT INTO chapters VALUES (686, '구의 방정식', '고등', '기하', '전체', '공간도형', '공간좌표');
