INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지1', '고등수학(상)-다항식-다항식의 연산');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지2', '고등수학(상)-다항식-나머지정리와 인수분해');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지3', '고등수학(상)-방정식과 부등식-복소수와 이차방정식');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지4', '고등수학(상)-방정식과 부등식-이차방정식과 이차함수');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지5', '고등수학(상)-방정식과 부등식-여러가지 방정식');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지6', '고등수학(상)-방정식과 부등식-여러가지 부등식');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지7', '고등수학(상)-도형의 방정식-평면좌표');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지8', '고등수학(상)-도형의 방정식-직선의 방정식');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지9', '고등수학(상)-도형의 방정식-원의 방정식');
INSERT INTO tests (test_name, test_comments) VALUES ('고등수학(상) 진단학습지10', '고등수학(상)-도형의 방정식-도형의 이동');
